Devices:
  <SWitch-Model>:
    type: ios-xe
    address: <IP_address>
    username: <USERNAME>
    password: <PASSWORD>
  <SWITCH-Model>:
    type: ios-xe
    address: <IP_address>
    username: <USERNAME>
    password: <PASSWORD>
