Devices:
  9200-L:
    type: ios-xe
    address: 10.64.71.62
    username: admin
    password: C!sco123@bgl11
  9300-48:
    type: ios-xe
    address: 10.64.71.36
    username: admin
    password: C!sco123@bgl11
